export const ADD_ERROE_MESSAGE = 'ADD_ERROE_MESSAGE';
export const REMOVE_ERROE_MESSAGE = 'REMOVE_ERROE_MESSAGE';

export const SAVE_TOKENINFO = 'SAVE_TOKENINFO';

export const SIDEBAR_TYPE = 'SIDEBAR_TYPE';
export const TOGGLE_DEVICE = 'TOGGLE_DEVICE';
export const SET_SIDEBAR_TYPE = 'SET_SIDEBAR_TYPE';

export const SET_TEST_INFO = 'SET_TEST_INFO';
export const INIT_LEVEL_DATA = 'INIT_LEVEL_DATA';
